project:
  type: website
  output-dir: docs

website:
  title: "model_guides"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Models"
        menu:
          - text: "Linear Regression"
            href: qmds/lm.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



