project:
  type: website
  output-dir: docs

website:
  title: "Model Guides for Biostatistics"
  favicon: thekids_logo.png
  navbar:
    logo: thekids_logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Models"
        menu:
          - text: "Linear Regression"
            href: qmds/lm.qmd

format:
  html:
    embed-resources: true
    code-fold: true
    toc: true
    toc-location: left
    html-table-processing: none
    self-contained: true
    mainfont: "Barlow"
    include-in-header:
      text: |
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Barlow&display=swap');
        </style>
reference-location: margin
citation-location: margin
css: styles.css



