project:
  type: website
  output-dir: docs

website:
  title: "model_guides"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Models"
        menu:
          - text: "Linear Regression"
            href: qmds/lm.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Models"
        contents:
          - qmds/lm.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



